# Base image of Apache Airflow
FROM apache/airflow:2.10.3

# Use user root for running installation
USER root

# Install dependencies for library PlayWright
RUN apt-get update && apt-get install -y \
    curl \
    docker.io \
    libx11-xcb1 \
    libglib2.0-0 \
    libnss3 \
    libatk1.0-0 \
    libgdk-pixbuf2.0-0 \
    libxcomposite1 \
    libxrandr2 \
    libasound2 \
    libpangocairo-1.0-0 \
    libatk-bridge2.0-0 \
    libxss1 \
    libappindicator3-1 \
    libnspr4 \
    libgbm1 \
    libdrm2 \
    && rm -rf /var/lib/apt/lists/*

# Checkout in user airflow. That need to make run installation of library
USER ${AIRFLOW_UID}

# Install library PlayWright in Python
RUN pip install playwright

# Install browsers for work in PlayWright
RUN playwright install
